TomneyWebApp/Areas/Astronomy/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TomneyWebApp.Areas.Astronomy.Controllers
{
    [Area("Astronomy")]
    public class HomeController : Controller
    {
        public IActionResult Default()
        {
            return View();
        }

        public IActionResult AstroBio()
        {
            return View();
        }
    }
}

TomneyWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using TomneyWebApp.Models;

namespace TomneyWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration _config;

        public HomeController(ILogger<HomeController> logger, IConfiguration config)
        {
            _logger = logger;
            _config = config;
        }

        public IActionResult Index()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View();
        }

        public IActionResult Default()
        {

            bool isFamily = false;
            Claim userId = User.Claims.FirstOrDefault(c => c.Type == "emails");
            if (userId != null)
            {
                _logger.LogInformation("Email claim for logged in user is {userId}", userId);
                if (userId.Value.ToLower().Contains("tomney"))
                {
                    isFamily = true;
                }
            }
            ViewBag.Secret = _config["mysql-staging"];
            ViewBag.IsFamily = isFamily;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TomneyWebApp/Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace TomneyWebApp.Controllers
{
    public class LinksController : Controller
    {
        // GET: LinksController
        public ActionResult Index()
        {
            return View();
        }

        //// GET: LinksController/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        //// GET: LinksController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: LinksController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: LinksController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: LinksController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: LinksController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: LinksController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

TomneyWebApp/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TomneyWebApp.Common.Interfaces;
using TomneyWebApp.Common.Interfaces.DataSrvc;

namespace TomneyWebApp.Controllers
{
    public class RecipeController : Controller
    {
        private IRecipeData _dataSrv;

        public RecipeController(IRecipeData dataSrc, ILogger<RecipeController> logger)
        {
            _dataSrv = dataSrc;
            logger.LogWarning("MyWarning");
        }

        // GET: RecipeController
        public ActionResult Default()
        {
            List<IRecipe> lst = _dataSrv.GetRecipesByName().ToList();
            ViewData["Recipes"] = lst;
            return View();
        }

        // GET: RecipeController/Details/5
        public FileStreamResult Details(string title)
        {
            IRecipe recipe = _dataSrv.GetRecipesByName(title).FirstOrDefault();
            var stream = new MemoryStream(recipe.Pdf);
            return new FileStreamResult(stream, "application/pdf");
        }

        //// GET: RecipeController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: RecipeController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: RecipeController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: RecipeController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: RecipeController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: RecipeController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

TomneyWebApp/Controllers/ScrapbookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace TomneyWebApp.Controllers
{
    public class ScrapbookController : Controller
    {
        // GET: ScrapbookController
        public ActionResult Default()
        {
            return View();
        }

        [Authorize]
        public ActionResult List()
        {
            return View();
        }

        [Authorize]
        public ActionResult Details(string album)
        {
            return View();
        }

        //// GET: ScrapbookController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: ScrapbookController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: ScrapbookController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: ScrapbookController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: ScrapbookController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: ScrapbookController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

TomneyWebApp/Controllers/TravelogueController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TomneyWebApp.Common;
using TomneyWebApp.Common.Interfaces;
using TomneyWebApp.Common.Interfaces.DataSrvc;
using TomneyWebApp.Models;

namespace TomneyWebApp.Controllers
{
    public class TravelogueController : Controller
    {
        private readonly ITravelogueData _dataSrvc;

        public TravelogueController(ITravelogueData dataSrvc)
        {
            _dataSrvc = dataSrvc;
        }

        // GET: TravelogueController
        public ActionResult Default()
        {
            List<ITravelogue> lst = _dataSrvc.GetAllTravelogues().ToList();
            ViewData["Travelogues"] = lst;
            return View();
        }

        public ActionResult Details(int id, string title)
        {
            TraveloguePage page = _dataSrvc.GetTraveloguePage(title, id);
            TraveloguePageVwMdl vm = new TraveloguePageVwMdl()
            {
                PriorPg = page.PriorPg,
                Parent = page.Parent,
                PgNum = page.PgNum,
                NextPg = page.NextPg,
                Html = page.Html
            };
            return View(vm);
        }

        //    // GET: TravelogueController/Create
        //    public ActionResult Create()
        //    {
        //        return View();
        //    }

        //    // POST: TravelogueController/Create
        //    [HttpPost]
        //    [ValidateAntiForgeryToken]
        //    public ActionResult Create(IFormCollection collection)
        //    {
        //        try
        //        {
        //            return RedirectToAction(nameof(Index));
        //        }
        //        catch
        //        {
        //            return View();
        //        }
        //    }

        //    // GET: TravelogueController/Edit/5
        //    public ActionResult Edit(int id)
        //    {
        //        return View();
        //    }

        //    // POST: TravelogueController/Edit/5
        //    [HttpPost]
        //    [ValidateAntiForgeryToken]
        //    public ActionResult Edit(int id, IFormCollection collection)
        //    {
        //        try
        //        {
        //            return RedirectToAction(nameof(Index));
        //        }
        //        catch
        //        {
        //            return View();
        //        }
        //    }

        //    // GET: TravelogueController/Delete/5
        //    public ActionResult Delete(int id)
        //    {
        //        return View();
        //    }

        //    // POST: TravelogueController/Delete/5
        //    [HttpPost]
        //    [ValidateAntiForgeryToken]
        //    public ActionResult Delete(int id, IFormCollection collection)
        //    {
        //        try
        //        {
        //            return RedirectToAction(nameof(Index));
        //        }
        //        catch
        //        {
        //            return View();
        //        }
        //    }
    }
}

TomneyWebApp/Views/Home/Default.cshtml
@model object

@{
    Layout = "_MyLayout";
}

<div class="container" style="margin-top: 30px">
    <div class="row" style="min-height: 300px">
        <div id="carouselExampleIndicators" class="carousel slide container" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="row">
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/02.jpg" alt="01">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/01.jpg" alt="02">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/03.jpg" alt="03">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="row">
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/04.jpg" alt="04">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/05.jpg" alt="05">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/06.jpg" alt="06">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="row">
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/07.jpg" alt="07">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/08.jpg" alt="08">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/09.jpg" alt="09">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="row">
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/10.jpg" alt="10">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/11.jpg" alt="11">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/12.jpg" alt="12">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="row">
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/13.jpg" alt="13">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/14.jpg" alt="14">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/15.jpg" alt="15">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="row">
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/16.jpg" alt="16">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/17.jpg" alt="17">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/18.jpg" alt="18">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="row">
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/19.jpg" alt="19">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/20.jpg" alt="20">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 d-md-block vert-space-sml">
                            <div class="card card-shadow">
                                <div class="card-body">
                                    <img class="img-fluid" src="~/images/home/21.jpg" alt="21">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

</div>

<div class="row">
    <div class="col-sm-4 text-right">
        <a class="btn btn-lg" asp-controller="Scrapbook">
            <i class="fas fa-book home-links"><span class="home-links">&nbsp;Scrapbook</span></i>
        </a><br />
        <a class="btn btn-lg" asp-controller="Recipe">
            <i class="fas fa-utensils home-links"><span class="home-links">&nbsp;Recipes</span></i>
        </a><br />
        <a class="btn btn-lg" asp-controller="Links" asp-action="Index">
            <i class="fas fa-link home-links"><span class="home-links">&nbsp;Our Links</span></i>
        </a>
    </div>
    <div class="col-sm-4">
        <div class="text-center">
            <img class="img-thumbnail" src="~/images/home/CloudTag2.png" alt="Tomney Cloud Tag" />
        </div>
    </div>
    <div class="col-sm-4 home-links">
        <a class="btn btn-lg" asp-area="Astronomy" asp-controller="Home" asp-action="Default">
            <i class="fas fa-moon home-links"><span class="home-links">&nbsp;Astronomy</span></i>
        </a>
        <a class="btn btn-lg" asp-controller="Travelogue" asp-action="Default">
            <i class="fas fa-suitcase home-links"><span class="home-links">&nbsp;Travelogue</span></i>
        </a>
        @if (ViewBag.IsFamily)
        {
            <a class="btn btn-lg" asp-page="/Travel/Index">
                <i class="fas fa-inbox home-links"><span class="home-links">&nbsp;Family Resources</span></i>
            </a>
        }
    </div>
</div>